image: "python:3.7"

before_script:
  - python --version
  - pip3 install -r requirements.txt

stages:
  - test


unittests:
  stage: test
  script:
    - python3 -m unittest discover -v worldoftanks/tests
  when:
    always
