image: "python:3.7"

before_script:
  - python --version
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - python3 -m pip install --user --upgrade setuptools wheel

stages:
  - test
  - make_build
  - deploy_test_pypi
  - deploy_pypi


unittest:
  stage: test
  script:
    - python3 -m unittest discover -v worldoftanks/tests
  when:
    manual

coveragetest:
  stage: test
  script:
    - coverage run --source=worldoftanks -m unittest discover -s worldoftanks/tests
    - coverage report -m
  when:
    manual

create_build:
  stage: make_build
  script:
    # Create config file
    - pip install twine
    - bash make_config.sh ${PYPI_USERNAME} ${PYPI_PASS} ${TEST_PYPI_USERNAME} ${TEST_PYPI_PASS}
    - pwd
    - ls -la
    - python3 setup.py sdist bdist_wheel
    - twine check dist/*
  when:
    manual

deploy_to_test:
  stage: deploy_test_pypi
  script:
    - cd worldoftanks
    - python3 -m twine upload --repository testpypi dist/* --verbose
  when:
    manual


deploy_to_live:
  stage: deploy_pypi
  script:
    - cd worldoftanks
    - python3 -m twine upload --repository pypi dist/* --verbose
  when:
    manual


