image: "python:3.7"

before_script:
  - python --version
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - python3 -m pip install --user --upgrade setuptools wheel

stages:
  - test
  - make_build
  - deploy_test_pypi
  - deploy_pypi


unittest:
  stage: test
  script:
    - python3 -m unittest discover -v worldoftanks/tests
  when:
    manual

coveragetest:
  stage: test
  script:
    - coverage run --source=worldoftanks -m unittest discover -s worldoftanks/tests
    - coverage report -m
  when:
    manual

create_build:
  stage: make_build
  script:
    - pip install twine
    - python3 setup.py sdist bdist_wheel
    - twine check dist/* --repository-url https://test.pypi.org/legacy/ --username $TWINE_USERNAME --password $TWINE_PASSWORD
  when:
    manual

deploy_to_test:
  stage: deploy_test_pypi
  script:
    - pip install twine
    - python3 setup.py sdist bdist_wheel
    - twine check dist/* --repository-url https://test.pypi.org/legacy/ --username $TWINE_USERNAME --password $TWINE_PASSWORD
    - twine upload dist/* --repository-url https://test.pypi.org/legacy/ --username $TWINE_USERNAME --password $TWINE_PASSWORD
  when:
    manual


deploy_to_live:
  stage: deploy_pypi
  script:
    - pip install twine
    - python3 setup.py sdist bdist_wheel
    - twine check dist/* --repository-url https://test.pypi.org/legacy/ --username $TWINE_USERNAME --password $TWINE_PASSWORD
    - twine upload dist/* --repository-url https://test.pypi.org/legacy/ --username $TWINE_USERNAME --password $TWINE_PASSWORD
  when:
    manual


